name: deploy ashiri to cpanel

on: 
    push: 
        branches: [main]

jobs: 
    deploy:
        name: deploy laravel 
        runs-on: ubuntu-latest
        steps:

            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.4'  
                extensions: mbstring, bcmath, xml, curl, zip, pdo, mysql
                tools: composer:v2
            - name: Install Composer dependencies
              run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
            - name: Use Node.js 22.17
              uses: actions/setup-node@v2
              with:
                node-version: '22.17'
            - name: 🔨 Build Project
              run: |
                npm install
                npm run build
            - name: Deploy to Shared Hosting via FTP
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                server: ${{ secrets.FTP_HOST }}
                username: ${{ secrets.FTP_USERNAME }}
                password: ${{ secrets.FTP_PASSWORD }}
                port: ${{ secrets.FTP_PORT }}
                protocol: ${{ secrets.FTP_PROTOCOL }}
                local-dir: ./
                server-dir: /samodunlade.com.ng/

            - name: Deployment Success Notification
              if: success()
              run: echo "Deployment completed successfully!"

            - name: Deployment Failure Notification
              if: failure()
              run: echo "Deployment failed. Please check the logs."